### ISSUE TITLE
Does not work on platforms aside from x86_64-linux

### ISSUE THREAD

**Issue by khaled** [hall/kubenix#12]
[This line](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/flake.nix#L22) seems to prevent this from working on other systems.

Any reason why it is this way?  I tried cloning the repo, uncommenting the line, and building the example on x86_86-darwin.  Seemed to work just fine.

**Comment by khaled** [comment]
> It's possibly due to docker images not being able to be built on darwin (at least not without extra work setting up a remote builder). However manifest generation should work just fine (as long as you don't use the docker module).

Agreed.  Also what about ARM systems?

**Comment by adrian-gierakowski** [comment]
any architecture supported by `nix` should be ok since manifests can be created with `nix eval` (`nix build` is only needed if you want to convert generate `json` to `yaml`).

**Comment by hall** [comment]
Thanks for the report, @khaled (and for the added details @adrian-gierakowski).

I'm not entirely certain as [the commit which introduced that change](https://github.com/hall/kubenix/commit/836fe9abd07f0cab92a12ebe0adbf47475f48848) has no details.

However, [the parent commit](https://github.com/hall/kubenix/commit/e7227cfe8cb0426936e1fb0e15e66a9471eea8b0) introduced new checks and failed [its CI execution](https://github.com/GTrunSec/kubenix/actions/runs/2083254255/jobs/3024923537) which was then [fixed by the commit in question](https://github.com/GTrunSec/kubenix/actions/runs/2083334331/jobs/3025044973). So, if I had to guess, the `x86_64-linux` restriction was likely introduced because the GH runners were unable to build those checks for [the other platforms](https://github.com/numtide/flake-utils/blob/5aed5285a952e0b949eb3ba02c12fa4fcfef535f/default.nix#L4-L6).

**Comment by hall** [comment]
Good find. First I'm hearing of [IFD](https://nixos.wiki/wiki/Import_From_Derivation) but that certainly appears to be the case as `./tests/k8s/imports.nix` (evaluated during checks) sets [`kubernetes.imports`](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/tests/k8s/imports.nix#L29) which [calls](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/modules/k8s.nix#L498) [`importYAML`](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/lib/upstreamables.nix), a wrapper around [`importJSON`](https://github.com/NixOS/nixpkgs/blob/7e146ca3e520a857c164d4fbf84b80e8631b6d4e/lib/trivial.nix#L313), which calls `readFile` and therefore qualifies as IFD per that wiki page.

Not yet sure what a decent resolution is here.


No idea on the darwin failure though; no surprise that it evaluates fine on linux:

```bash
nix-repl> builtins.match "(  |)+" ""
[ "" ]
```

Presumably it's using a different regex engine but will have to do some work before I can get to a place to test.

**Comment by adrian-gierakowski** [comment]
> ./tests/k8s/imports.nix (evaluated during checks) sets [kubernetes.imports](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/tests/k8s/imports.nix#L29) which [calls](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/modules/k8s.nix#L498) [importYAML](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/lib/upstreamables.nix), a wrapper around [importJSON](https://github.com/NixOS/nixpkgs/blob/7e146ca3e520a857c164d4fbf84b80e8631b6d4e/lib/trivial.nix#L313), which calls readFile and therefore qualifies as IFD per that wiki page.

Just to clarify, the `IFD` is due to the call to `readFile` on the output of [pkgs.runCommand ](https://github.com/hall/kubenix/blob/5260d2a014bdccc9404877e12074aa9856f35a1b/lib/upstreamables.nix#L13) withi `importYaml`. `runCommand` produces a derivation, and so `readFile` ends up loading the content of the output of building that derivation from the `/nix/store`. 

`importJSON` itself doesn't cause IFD (as long as it's called with a path to a file which exists at evaluation time, and not a derivation, which needs to be built first by nix). 

The way to get rid of `IFD` here would be to implement a yaml parser in pure `nix` (or have it implemented as `nix` builtin). Alternatively you could convert you yaml manifests to json and use `importJSON` instead of `importYaml`.

**Comment by hall** [comment]
Ah! Thanks, that makes sense.

A quick search doesn't reveal much in the way of complete parsers in pure `nix` (and I'm not particularly itching to try and write one). I don't use either of the import functions myself but I can see `importYaml` being useful (instead of requiring users to convert to `json` beforehand, e.g.).

There _is_ [a recent MR inflight to implement `fromYAML`](https://github.com/NixOS/nix/pull/7340). So maybe a proper solution isn't far off.

I'm tempted to just disable the `yaml` test for the time-being so users on other platforms can at least still use the project.

**Comment by adrian-gierakowski** [comment]
> I'm tempted to just disable the `yaml` test for the time-being so users on other platforms can at least still use the project.

👍

**Comment by hall** [comment]
Cool -- thanks for the sanity check. I've disabled the import test (didn't help to only disable `yaml` without `json`) in https://github.com/hall/kubenix/commit/7201c3229f0d9f21e3d7e018dd5f4f9d245bed58 and switched to `eachDefaultSystem` in https://github.com/hall/kubenix/commit/7af982c404f26bc299e27872308aea411f0f1502.

@khaled, closing as this should be complete but let us know if it doesn't work as expected.

**Comment by khaled** [comment]
Thanks @hall and @adrian-gierakowski!  `nix flake check` now succeeds on x86_64-linux.  The regex failure is still a problem on darwin, but I guess that's a separate bug :)

**Comment by hall** [comment]
Yeah, feel free to open another issue for that. Best I can do is help you debug on darwin. The idea is that regex is removing "empty" lines (where that includes whitespace characters). It appears to be a known issue that [there are inconsistencies between platforms](https://github.com/NixOS/nix/issues/1537).

You might try the following diff :shrug: (this line also appears in the istio generator in the same parent directory)

```diff
❯ git diff jobs/generators/k8s/
diff --git a/jobs/generators/k8s/default.nix b/jobs/generators/k8s/default.nix
index 43ec4b9..e712742 100644
--- a/jobs/generators/k8s/default.nix
+++ b/jobs/generators/k8s/default.nix
@@ -21,7 +21,7 @@ with lib; let
       then "null"
       else builtins.toString value;
 
-    removeEmptyLines = str: concatStringsSep "\n" (filter (l: (builtins.match "(  |)+" l) == null) (splitString "\n" str));
+    removeEmptyLines = str: concatStringsSep "\n" (filter (l: (builtins.match "[[:space:]]*" l) != []) (splitString "\n" str));
 
     mkOption = {
       description ? null,
```

You can either test in `nix repl` (e.g., `builtins.match "[[:space:]]*"  ""`) or execute `nix run '.#generate'` and if there's no diff under `./modules/generated`, then it works as expected.

**Comment by felixscheinost** [comment]
I am trying to implement a change to the Helm module we discussed (implement filtering/modifying the objects).

I am trying to get the currently commented out test working on my machine, a aarch64-darwin but with `x86_64-darwin` support through Rosetta and also `x86_64-linux` and `aarch64-linux` remote builders configured.

If I understand correctly the commented out tests prevent running the checks even on `aarch64-linux`, right? That doesn't seem right, I agree.

What I am unsure about though is what the expectation is about Darwin:

- Do you expect that Darwin users without a Linux remote builder configured are able to execute *all* tests? 
   - I think that shouldn't be the case as then integration tests, like are already present, are out of the picture right?
- `nix flake check` executes checks for the current arch, right? So would it make sense that on Darwin `nix flake check` only does the manifest tests but on Linux additional integration tests are executed?
   - But: How could developers on Darwin with remote builders configured run the Linux tests then? Does `nix flake check` allow to specify the system? I tried `nix flake check .#checks.x86_64-linux` and some variations of that but that doesn't seem to work.

**Comment by hall** [comment]
> If I understand correctly the commented out tests prevent running the checks even on `aarch64-linux`, right?

Since the commented out tests use IFD, it forces evaluation on every platform the flake supports (i.e., the ones defined by [`eachDefaultSystem`](https://github.com/hall/kubenix/blob/5bcab30ed204bfbf8ff6a37e67af154ff8aac16e/flake.nix#L21)). That means whenever running `nix flake check`, access must be available to a set of machines which cover _every_ system. So anyone without access to at least one builder in `eachDefaultSystem` will fail the checks.

Ideally, we'd remove the use of IFD and `nix flake check` would execute only for the local platform.

You're saying that existing integration tests don't support darwin? It's unclear to me in general how well nix is supported on darwin. Which tests? Can you provide an example or links to docs?

I haven't tried running the checks for a specific platform; maybe `nix flake check --system x86_64-linux`?

**Comment by felixscheinost** [comment]
> Since the commented out tests use IFD, it forces evaluation on every platform the flake supports

Hmm, are  you sure that this is really true? Wouldn't it also mean that it would try to evaluate `x86_64-darwin` on `x86_64-linux`? Even on the revision of `flake-utils` currently used by this project the default systems contained the darwin systems (see [flake-utils](https://github.com/numtide/flake-utils/blob/c0e246b9b83f637f4681389ecabcb2681b4f3af0/default.nix#L3))

> Ideally, we'd remove the use of IFD and nix flake check would execute only for the local platform.

I think that sounds like a good idea as it seems that IFD is sort of a discouraged. Maybe this might also reduce resource usage of kubenix? I previously tried running `nix flake check` on a small Linux VM and `nix flake check` got killled as it quickly used >2GB RAM. 

> You're saying that existing integration tests don't support darwin?

I don't know to be honest. But I assume so? Because the integration tests actually test against a real Kubernetes cluster running in a VM I assume? Using NixOS VM testing capability? Or is that assumption wrong?

NixOS VM tests currently don't work properly on macOS as they are optimized for speed: they share the `/nix` store with the host which is hard or impossible to implement on macOS AFAIK.

I haven't looked through all tests but those that are currently commented out due to IFD are definitely integration test, right? Are there any other integration tests that aren't commented out?

As of right now `nix flake check` succeeds on my Darwin machine, with Linux builders configured.

> It's unclear to me in general how well nix is supported on darwin.

I would say Darwin support is very good already and only getting better (partly due to e.g. https://opencollective.com/nix-macos)

We use it as an alternative to `brew`. Except for e.g. heavy GUI tools like Slack, Docker Desktop, ... all the CLI tools come from Nix. Most of `nixpkgs` is also available on Darwin and most of it is also built and cached by Hydra.

If I stumble into a random `nix-shell` out there most of the time it also works on Darwin, which is great!

For working with NixOS servers though you most of the time need to have a Linux remote builder configured. In my case this was a container running in Docker for Desktops VM but I am in the process of migrating that into the "official" `darwin.builder` that nixpkgs recently added.

---

`nix flake check` is only supposed to be executed by people working on the `kubenix` project itself, right? Not downstream users of the library? In this case I think it would be okay to assume someone to need a Linux builder configured for that on Darwin. This way developers on all platforms would only need to execute `nix flake build` to execute the whole test suit.

**Comment by adrian-gierakowski** [comment]
> > Since the commented out tests use IFD, it forces evaluation on every platform the flake supports
> 
> Hmm, are you sure that this is really true? Wouldn't it also mean that it would try to evaluate `x86_64-darwin` on `x86_64-linux`? 

see: https://github.com/NixOS/nix/issues/4265
although there seems to be a fix in the works: https://github.com/NixOS/nix/pull/7759


> 
> > Ideally, we'd remove the use of IFD and nix flake check would execute only for the local platform.
> 

Helm module [does IFD](https://github.com/hall/kubenix/blob/b2feaf6b405e38c632c70d65f134ac02a1ba0600/modules/helm.nix#L97), there is no other way to do what it does and we definitely want tests to cover it.

The other place I'm aware of IFD being used is converting json to yaml (as mentioned [above](https://github.com/hall/kubenix/issues/12#issuecomment-1406199508)). This is not an essential feature imho.

Anyway, with the fix mentioned above we can stop worrying about IFD

>  `nix flake check` got killled as it quickly used >2GB RAM.

I don't think that is related to IFD, but rather the fact that it spins up nixos tests which run in a VM

> 
> > You're saying that existing integration tests don't support darwin?
> 
> I don't know to be honest. But I assume so? Because the integration tests actually test against a real Kubernetes cluster running in a VM I assume? Using NixOS VM testing capability? Or is that assumption wrong?

That is correct.

> NixOS VM tests currently don't work properly on macOS as they are optimized for speed: they share the `/nix` store with the host which is hard or impossible to implement on macOS AFAIK.

I believe this has been [solved recently](https://github.com/NixOS/nixpkgs/issues/108984). 

> `nix flake check` is only supposed to be executed by people working on the `kubenix` project itself, right? Not downstream users of the library?

yes

**Comment by felixscheinost** [comment]
> Helm module [does IFD](https://github.com/hall/kubenix/blob/b2feaf6b405e38c632c70d65f134ac02a1ba0600/modules/helm.nix#L97), there is no other way to do what it does and we definitely want tests to cover it.

Makes sense! 

> I don't think that is related to IFD, but rather the fact that it spins up nixos tests which run in a VM

True, that is more likely to be the reason. I just remember playing around with IFD myself sometime ago and running into very slow evaluation times as well but I may have jumped to conclusions here 😄 

> I believe this has been solved recently.

Ah yeah, that's right. Hmm, I think I remember though that building the SquashFS for the root partition can be quite slow. If a Linux builder is available, the edit-test-cycle is probably quicker using that, compared to always having to build a whole new image.

I will try to get the Helm integration test working on Darwin when I have time 😃

> I'm tempted to just disable the yaml test for the time-being so users on other platforms can at least still use the project.

> Cool -- thanks for the sanity check. I've disabled the import test (didn't help to only disable yaml without json) in https://github.com/hall/kubenix/commit/7201c3229f0d9f21e3d7e018dd5f4f9d245bed58 and switched to eachDefaultSystem in https://github.com/hall/kubenix/commit/7af982c404f26bc299e27872308aea411f0f1502.

But a prerequisite for re-enabling that test would be to find a different workaround than disabling the test, right? I'll play around with that as well.
